name: CI || fiskaly .NET SDK

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1

    - name: Install dependencies
      run: nuget restore Fiskaly/SDK/SDK.standard.csproj

    - name: Build fiskaly .NET SDK
      run: dotnet build --configuration Release --no-restore Fiskaly/SDK/SDK.standard.csproj

  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nuget/setup-nuget@v1

    - name: Run SDK Unit-Tests
      shell: pwsh
      run: |
        cd Fiskaly/SDK.Tests
        wget https://storage.googleapis.com/download/storage/v1/b/fiskaly-cdn/o/clients%2Fcom.fiskaly.client-windows-amd64-v1.1.400.dll?generation=1587652227126443&alt=media
        copy com.fiskaly.client-windows-amd64-v1.1.400.dll bin/Release/netcoreapp.3.1/
        dotnet test Fiskaly/SDK.Tests/SDK.Tests.csproj

